### ISSUE TITLE
The submit.csv is empty?

### ISSUE THREAD

**Issue by HorizonLiang** [dmksjfl/Job_Shop_Scheduling_Problem_with_Reinforcement_Learning#1]
When I finish running the program，The generated submit.csv file is empty.

**Comment by guokai-hh** [comment]
I would like to ask if there is a visualization diagram?For example, the reward function line chart?

**Comment by dmksjfl** [comment]
> When I finish running the program，The generated submit.csv file is empty.

Please check the file path. For a fast check, use `max-episode-length` 10 to see whether a `submit.csv` is generated. FYI, the csv file is generated during my local test.

**Comment by dmksjfl** [comment]
> I would like to ask if there is a visualization diagram?For example, the reward function line chart?

The visualization is not conducted, as the left jobs would be fewer if the reward is larger. For research purpose, you can visualize the reward chart or design your own reward function to handle it, which, however, is out of the scope of this project.
